[package]
name = "pest-site"
version = "0.1.0"
authors = ["Dragoș Tiselice <dragostiselice@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
pest = "2.5"
pest_meta = "2.5"
pest_vm = "2.5"
wasm-bindgen = "0.2"
serde-wasm-bindgen = "0.4"

[dependencies.web-sys]
version = "0.3"
features = [
    "Window",
    "Document",
    "Text",
    "DomTokenList",
    "HtmlOptionElement",
    "HtmlSelectElement",
    "HtmlTextAreaElement",
    "HtmlCollection",
    "InputEvent",
]
